WORK_DIR: "~/Desktop/sequence_ml"

testinput: "testInput.txt"
testout: "testOut.txt"

# All Python scripts used to process the data
PythonScripts:
  TestRscript: testscript.R


#test data files
data:
    testdata1: ['data/testseq.txt','data/testsig.txt']